# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += \
			  imx6ull-microgea-microdev.dtb \
			  imx6ull-microgea-microdev-lcd7.dtb \
			  imx6ull-microgea-microdev-lcd10.dtb \
			  imx6ull-microgea-microdev-rev3.dtb \

dtb-$(CONFIG_SOC_IMX6Q) += \
			  imx6dl-icore-starterkit-v2.dtb \
			  imx6q-icore-starterkit-v2.dtb
