# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += \
			  imx8mm-icore-ctouch2.dtb \
			  imx8mm-icore-starterkit.dtb \
			  imx8mp-icore-2e-net-phy.dtb \
			  imx8mp-icore-2e-ctouch2.dtb \
			  imx8mp-icore-2e-starterkit.dtb \
			  imx8mp-icore-ctouch2.dtb \
			  imx8mp-icore-fasteth-ctouch2.dtb \
			  imx8mp-icore-fasteth-starterkit.dtb \
			  imx8mp-icore-starterkit.dtb \
			  imx8mp-smarcore-xtouch2.dtb \
			  imx8ulp-microgea-microdev-yes7.dtb \
			  imx93-icore-ctouch2.dtb \
			  imx93-icore-starterkit.dtb
